modkey = "Mod3"
mousekey = "Mod3"
tags = [ "1", "2", "3", "4" ]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

[[workspaces]]
y = 0
x = 0
height = 1440
width = 2560

[[workspaces]]
y = 0
x = 2560
height = 2560
width = 1440


[[keybind]]
command = "CloseWindow"
modifier = ["Control"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[scratchpad]]
name = "scratch" # This is the name which is referenced when calling (case-sensitive)
value = "kitty" # The command to load the application if it isn't started

[[keybind]]
command = "ToggleScratchPad"
value = "scratch" # Name set for the scratchpad
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "SetLayout"
value = "MainAndDeck"
modifier = ["modkey"]
key = "y"

[[keybind]]
command = "SetLayout"
value = "MainAndVertStack"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"


[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"
